name: engolf
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 4.0.5+77

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^1.20.1
  firebase_analytics: ^9.3.1
  firebase_performance: ^0.8.2+2
  firebase_crashlytics: ^2.8.7
  google_mobile_ads: ^2.2.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

  provider: ^6.0.3
  rxdart: ^0.27.4
  english_words: ^4.0.0
  flutter_lorem: ^2.0.0
  arkit_plugin: ^1.0.5
  flutter_staggered_animations: ^1.0.0
  pedantic_mono: ^1.19.2
  flare_flutter: ^3.0.2
  flutter_inappwebview: ^5.4.3+7
  package_info: ^2.0.2
  app_tracking_transparency: ^2.0.2+4
  flutter_svg: ^1.1.1+1
  shared_preferences: ^2.0.15
  keyboard_actions: ^4.0.1
  share_extend: ^2.0.0
  path_provider: ^2.0.11
  auto_size_text: ^3.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  lottie: ^1.3.0
  material_floating_search_bar: ^0.3.7
  logger:
  floor: ^1.3.0
  collection: ^1.15.0-nullsafety.4
  awesome_dialog: ^2.2.1
  in_app_review: ^2.0.4
  fl_chart:
  font_awesome_flutter:
  timeago:
  json_path:
  google_fonts:
  flutter_spinkit:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11

  floor_generator: ^1.3.0
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.2.3+1


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  image: "assets/icon/logo_engolf_v2_512.png"
  color: "#151A13"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
