name: engolf
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 4.1.0+100

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^3.8.0
  firebase_analytics: ^11.3.5
  firebase_performance: ^0.10.0+10
  firebase_remote_config: ^5.1.5
  firebase_crashlytics: ^4.1.5
  google_mobile_ads: ^5.2.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  provider: ^6.1.4
  rxdart: ^0.28.0
  english_words: ^4.0.0
  flutter_lorem: ^2.0.0
  arkit_plugin: ^1.1.0
  flutter_staggered_animations: ^1.1.1
  pedantic_mono:
  flare_flutter:
    git:
      url: https://github.com/mbfakourii/Flare-Flutter.git
      path: flare_flutter
      ref: remove_hashValues
  flutter_inappwebview: ^6.1.5
  package_info_plus: ^8.3.0
  app_tracking_transparency: ^2.0.6+1
  flutter_svg: ^2.0.14
  shared_preferences: ^2.5.3
  keyboard_actions: ^4.2.0
  share_extend:
    git:
      url: https://github.com/Tetsukick/ShareExtend.git
      ref: 1784b75595776fa9c491b64ecba1b4febf00d7f9
  path_provider: ^2.1.5
  auto_size_text: ^3.0.0
  intl: ^0.19.0
  lottie: ^3.3.1
  material_floating_search_bar_2:
  logger:
  floor: ^1.5.0
  collection: ^1.19.0
  awesome_dialog: ^3.2.1
  in_app_review: ^2.0.10
  fl_chart: ^0.69.0
  font_awesome_flutter:
  timeago:
  json_path:
  google_fonts: ^6.2.1
  flutter_spinkit:
  file: ^7.0.1
  url_launcher: ^6.3.1
  sizer: ^3.0.5

dev_dependencies:
  build_runner: ^2.4.13

  floor_generator: ^1.5.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.2

dependency_overrides:
  platform: ^3.1.6

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  image: "assets/icon/logo_engolf_v2_512.png"
  color: "#151A13"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
